Gandi/gandi.cli

README.md

add travis build status

---

README.md
gandi/cli/commands/record.py
gandi/cli/modules/record.py

Records deletion : delete records by name, value or type for a zone file
Records update : update an entire zone file from a file. Use a file is a good way to have a short command line and edit multiple records in one shot.
Use case : 
`gandi zone list example.com --output`
`vi example.com_123465`
[...] Update zone file
`gandi zone update example.com --file example.com_123465`
Push and activate the new zone file

Update and delete zone records

---

CONTRIBUTING.md
README.md

Partially inspired by [Docker's contribution guidelines](https://github.com/docker/docker/blob/master/CONTRIBUTING.md).

Create more detailed contribution guidelines

---

README.md

New link for virtualenv installation. The old one give a "Page not Found"..

Update README.md : New link for virtualenv installation.

---

gandi.completion

In #92 we refer to bash completion.We talked about using a click-compatible completion module. In the meantime, here's my temporary workaround.

Completion

---

gandi/cli/commands/ip.py
gandi/cli/modules/network.py
gandicli.man.rst

Should satisfy #101 and #102 
Also added ip list --vlan for convenience while in that code region

IP address reverse name and vlan filtering

---

index.html

Update the copyright notice to 2015

Hey, we're in 2015 now :)

---

README.md
gandi/cli/commands/record.py
gandi/cli/modules/record.py

list: '--output' is now deprecated and replace by '--format'
update : Add method to update only one record in the zone file
Doc : Update documentation for record and copyright 2015

Record enhancement on list and update + doc

---

gandi/cli/modules/iaas.py

Now we have a script param for vm creation calls, use this.

upload script to API

---

gandi/cli/commands/disk.py
gandi/cli/modules/disk.py
gandicli.man.rst

This is my attempt to address issue #114 
I wasn't able to build the docs as I don't have rst2man.

Diskattach

---

gandi/cli/core/base.py
gandi/cli/core/cli.py
gandi/cli/core/client.py
gandi/cli/core/params.py
gandi/cli/core/utils/xmlrpc.py
gandi/cli/modules/account.py
gandi/cli/modules/status.py

compatibility with python3

---

gandi/cli/tests/commands/test_certificate.py
gandi/cli/tests/commands/test_disk.py
gandi/cli/tests/commands/test_domain.py
gandi/cli/tests/fixtures/_domain.py

Add tests for domain list and info commands

Tests domain

---

gandi/cli/commands/domain.py
gandi/cli/core/utils/__init__.py
gandi/cli/modules/domain.py
gandi/cli/tests/commands/test_certificate.py
gandi/cli/tests/commands/test_disk.py
gandi/cli/tests/commands/test_domain.py
gandi/cli/tests/fixtures/_contact.py
gandi/cli/tests/fixtures/_domain.py

Warning: maybe break something !
I move the callback for check domain available for testing purpose.
Can you look and test that i don't break something for domain.create ?

Tests domain create

---

gandi/cli/commands/certificate.py
gandi/cli/commands/disk.py
gandi/cli/commands/docker.py
gandi/cli/commands/paas.py
gandi/cli/core/base.py
gandi/cli/core/utils/__init__.py
gandi/cli/core/utils/unixpipe.py
gandi/cli/modules/cert.py
gandi/cli/tests/commands/test_certificate.py
gandi/cli/tests/commands/test_disk.py
gandi/cli/tests/fixtures/_cert.py
gandi/cli/tests/fixtures/_hosting.py
gandi/cli/tests/fixtures/mocks.py

run PEP8 on files

---

gandi/cli/commands/webacc.py
gandi/cli/core/params.py
gandi/cli/modules/domain.py
gandi/cli/modules/iaas.py
gandi/cli/modules/paas.py

Various errors

---

packages/archlinux/.gitignore
packages/archlinux/PKGBUILD

I didn't enforce click<=4.0 from setup.py because it's working fine here with 4.0.

Updated Arch Linux package to v0.14

---

gandi/cli/modules/iaas.py

In case the server is responding with a connection refused, wait one second since the error is immediate

Be less aggressive while trying to connect via SSH

---

packages/archlinux/PKGBUILD

Switched tests to nosetests.
See #181.

Updated Arch Linux package to v0.18

---

gandi/cli/core/utils/__init__.py

Salut,
J'utilise beaucoup les alias et il est difficile de s'y retrouver au bout d'un certains nombre, possible de trier par ordre alphabétique pour faciliter la lecture ?
Merci :)

sort aliases

---

gandi/cli/core/utils/unixpipe.py

Everything we need is in os. This fixes an import error for
this pretty much unused module on non posix operating systems.
Should help #190

Remove usage of posix

---

gandi/cli/commands/ip.py
gandi/cli/commands/vlan.py
gandi/cli/commands/vm.py

Help reports bad units. it's kbits/s not bit/s

---

gandi/cli/modules/iaas.py

Do a sleep(1) anyway when the error we get trying to connect to a newly
created VM is not ECONNREFUSED.
When trying to connect to an IPv6 host, the error may be EHOSTUNREACH
instead for example

Iaas.wait_for_sshd: be more CPU friendly

---

MANIFEST.in

Fix open issue 243: https://github.com/Gandi/gandi.cli/issues/243
Signed-off-by: aegiap <aegiap@gandi.net>

Add helper and documentation in release tarball

---

gandi/cli/commands/paas.py
gandi/cli/commands/vm.py
gandi/cli/commands/webacc.py
gandi/cli/core/cli.py
gandi/cli/core/params.py
gandi/cli/core/utils/unixpipe.py
gandi/cli/modules/cert.py
gandi/cli/modules/status.py
gandi/cli/tests/commands/test_paas.py
gandi/cli/tests/commands/test_status.py
setup.py

Just clean code with pycodestyle

pycodestyle check

---

setup.py

the problem is in issue https://github.com/Gandi/gandi.cli/issues/268

Add dep click < 6.7

---

.travis.yml

see https://github.com/travis-ci/travis-ci/issues/9815

Use real python 3.7 from travis

---

README.md

Current code status will be clearer

Move badges on top of the README

---

gandi/cli/core/params.py
gandi/cli/tests/commands/test_dnssec.py

[dnssec] algorithm and flags must be string
